// DAY 4 - C_07
/* TOPICS : CONSTANTS IN C
1. CONSTANTS IN C
2. TYPES OF CONSTANTS : 
   a. NUMERIC : 
       i. INTEGER
       ii. FLOATING 
   b. CHARACTER:
       i. SINGLE CHARACTER 
       ii. STRING CONSTANT 
*/
// DATED - 04/06/2026

// THEORY OF CONSTANT IN C PROGRAM 
// RULES AND DIFFERENCES OF CONSTANTS 