// D3 - C_06
// TOPIC - EXECUTION OF C PROGRAM 
// DATED - 03/06/2026

// FLOW CHART OF EXECUTION OF C PROGRAM 

/* STEPS OF EXECUTION OF C PROGRAM 
1. EDITING
2. COMPILATION 
3. LINKING 
4. LOADING 
5. EXECUTION */