// DAY 3 - C_05
/* TOPIC : STRUCTURE OF C PROGRAM
1. DOCUMENTATION SECTION 
2. LINK SECTION
3. DEFINITION SECTION
4. GLOBAL DECLARATION SECTION
5. MAIN SECTION
6. SUB PROGRAM SECTION 
*/
// DATED - 03/06/2026

// PRINT HELLO WORLD 
#include <stdio.h>
int main()
{
    printf("Hello World");
    getch()
}
getch();
